[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ibl-utils"
version = "0.1.0"
description = "utils.stepcheck extension"
requires-python = ">=3.9"
dependencies = ["ipywidgets>=8"]

[tool.hatch.build.targets.wheel]
packages = ["utils"]
